---
abstract: 'Create packages(rpm, deb) from perl modules'
author:
  - 'Takatoshi Kitano <kitano.tk@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Base: 0
  Test::Class: 0
  Test::LoadAllModules: 0.02
  Test::More: 0.92
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Packager
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  Archive::Tar: 0
  Cwd: 0
  File::Basename: 0
  File::Copy: 0
  File::Temp: 0
  RPM::Specfile: 0
  URI::Escape: 0
requires:
  Archive::Extract: 0
  CPANPLUS::Backend: 0
  Class::Inspector: 0
  File::Copy: 0
  FindBin::libs: 0
  Hash::Merge: 0
  IPC::System::Simple: 0
  Kwalify: 1.20
  LWP::UserAgent: 0
  List::Compare: 0
  List::MoreUtils: 0
  Module::CoreList: 2.17
  Module::Depends: 0
  Mouse: 0.17
  MouseX::Getopt: 0.04
  Path::Class: 0
  Pod::POM: 0
  UNIVERSAL::require: 0
  URI: 0
  YAML: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.074
