---
abstract: 'Create packages(rpm, deb) from perl modules'
author:
  - 'Takatoshi Kitano <kitano.tk@gmail.com>'
build_requires:
  Module::Install::AuthorTests: 0
  Test::Base: 0
  Test::Class: 0
  Test::LoadAllModules: 0.02
  Test::More: 0
  Test::Requires: 0
distribution_type: module
generated_by: 'Module::Install version 0.72'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: CPAN-Packager
no_index:
  directory:
    - inc
    - t
requires:
  CPANPLUS::Backend: 0
  Class::Inspector: 0
  File::Copy: 0
  FindBin::libs: 0
  Hash::Merge: 0
  IPC::System::Simple: 0
  LWP::Simple: 0
  LWP::UserAgent: 0
  List::Compare: 0
  List::MoreUtils: 0
  Module::CoreList: 2.17
  Module::Depends: 0
  Mouse: 0.17
  MouseX::Getopt: 0.04
  Path::Class: 0
  Pod::POM: 0
  RPM::Specfile: 0
  UNIVERSAL::require: 0
  YAML: 0
  perl: 5.8.0
tests: 't/*.t t/0*/*.t xt/*.t'
version: 0.054
